sudo: required
services:
  - docker

before_install:
  - docker build -t dalmer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dalmer/react-test npm test

after_success:
  - docker build -t dalmer/multi-client ./client
  - docker build -t dalmer/multi-nginx ./nginx
  - docker build -t dalmer/multi-server ./server
  - docker build -t dalmer/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to dockerhub
  - docker push dalmer/multi-client
  - docker push dalmer/multi-nginx
  - docker push dalmer/multi-server
  - docker push dalmer/multi-worker

  

